### ISSUE TITLE
Restaurant card element

### ISSUE THREAD

**Issue by rainabozhi** [rainabozhi/Special_Order#1]
## Add a restaurant card

As a user on the search for suitable places to dine out I want to see a card of a restaurant which gives me basic information- the name, an adress, phone number and a picture so I can find it. 

## Acceptance criteria
- [ ] (A picture and the Name of the restaurant is displayed)
- [ ] (The address is displayed)
- [ ] (The phone number is displayed)

## Tasks
- [ ] (Set up a restaurant component)
- [ ] (Set prop types)
- [ ] (Integrate component into app)

## Size
(small)
