### ISSUE TITLE
diatary preferences

### ISSUE THREAD

**Issue by rainabozhi** [rainabozhi/Special_Order#3]
## Value statement

As a **Guest**
I need **a list of diatary preferences**
so that **I find the right restaurants for me**

## Acceptance criteria
- [ ] tags are lowercase
- [ ] tags are styled like in the design
- [ ] characters are limited to 80, then dotted out (hidden)

## Tasks
- [ ] create tag component (in storybook)
- [ ] add styling
- [ ] add tags to Restaurant cards

## Size
small
