### ISSUE TITLE
Styling landing page

### ISSUE THREAD

**Issue by rainabozhi** [rainabozhi/Special_Order#4]
## 

As a **guest**
I need **to see a landing page that helps me find the most useful information I need**
so that **I can save time.**

## Acceptance criteria
- [ ] (Elements are styled in a way that displays the general design of the app)
- [ ] (Color scheme is chosen)
- [ ] (page is responsive on different screens)

## Tasks
- [ ] (learn more about Styled Components)
- [ ] (Apply styles to reusable components)

## Size
(small)
