### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by rainabozhi** [rainabozhi/Special_Order#8]
## Search bar

As a **user**
I need **Search bar**
so that **I can find spots close to me**

## Acceptance criteria
- [ ] (Search bar is styled accordingly)
- [ ] (a button to initiate search is added)
- [ ] (fuzzy search is integrated)
- [ ] (search bar is positioned relatively)

## Tasks
- [ ] (find ways to search through)
- [ ] (show found items)

## Size
(medium)
