### ISSUE TITLE
Add data to detailed menu view

### ISSUE THREAD

**Issue by rainabozhi** [rainabozhi/Special_Order#9]
## Add Menu items

As a **(user)**
I need **(a detailed list with dishes for each restaurant)**
so that **(I can make an informed choice when I order)**

## Acceptance criteria
- [ ] (added specific items to detailed menu list for each restuarant)

## Tasks
- [ ] (add json data to existing array)
- [ ] (iterate through items)
- [ ] (show items on detailed menu page]

## Size
(medium)
